# yumパッケージアップデート
- name: yum update
  yum:
    name: '*'
    update_cache: yes
    state: latest

# ロケール
- name: set locale
  shell: localectl set-locale LANG=ja.JP.utf8

# タイムゾーン
- name: set timezone
  timezone:
    name: Asia/Tokyo

# NTPサーバ設定
- name: upload chrony.conf
  template:
  src: chrony.conf
  dest: /etc/chrony.conf
  owner: root
  group: root
  mode: 0544
  force: yes
  backup: yes

# chronyd再起動
- name: restart chronyd
  service:
    name: chronyd
    state: restarted