- name: install package
  yum:
    name: "{{ items }}"
    state: latest
  vars:
    items:
      - git
      - bzip2
      - gcc
      - openssl-devel
      - readline-devel
      - zlib-devel

# やること：apache-loggenのAnsible記載
