---
- hosts: vagrants
  become: true
  user: vagrant
  tasks:
#    - name: yum update
#      yum:
#        name: '*'
#        update_cache: yes
#        state: latest
    - name: install httpd
      yum:
        name: httpd
        update_cache: yes
        state: latest
    - name: install epel
      yum:
        name: epel-release
        update_cache: yes
        state: latest
