---
- hosts: vagrant
  become: true
  user: vagrant
  vars:
    # PHP情報
    install_php:
      # PHPバージョン
      ver: php74
      # インストールPHPパッケージ
      install_products:
        - php
        - php-curl
        - php-gd
        - php-cli
        - php-mysql
        - php-xml
        - php-mbstring

    # MySQL情報
    install_mysql:
      # MySQLバージョン
      ver: mysql57
      # インストールMySQLパッケージ
      install_products:
        - mysql-community-client
        - mysql-community-server
        - mysql-community-common
        - mysql-community-libs
        - mysql-community-libs-compat
        - MySQL-python
      # 特権パスワード
      root_password: Vagrant@1
      # 作成ユーザ名
      db_username: matomo
      # 作成ユーザパスワード
      db_password: Vagrant@1
      # 作成DB
      db_name: matomo

    # Ruby情報
    install_ruby:
      # Rubyバージョン
      ver: 2.7.1
      # インストールRuby前提パッケージ
      install_products:
        - git
        - bzip2
        - gcc
        - openssl-devel
        - readline-devel
        - zlib-devel
      # インストールgemパッケージ
      install_gem_products:
        - apache-loggen

  # ロール
  roles:
    - common
    - php
    - apache
    - mysql
    - matomo
    # apache-loggen利用するためRubyインストール
    - ruby
